# Generated by Django 4.1.1 on 2022-10-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('barcode', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockOrderForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stockorder')),
            ],
        ),
        migrations.AddField(
            model_name='stockorder',
            name='products',
            field=models.ManyToManyField(through='products.StockOrderForProduct', to='products.product'),
        ),
    ]
